server:
  port: 1211

spring:
  #mail
  mail:
    host: smtp.163.com
    username: 13891655545@163.com
    password: JVOEXUUTLQQPUASV
    default-encoding: UTF-8
    port: 465
  datasource:
    url: jdbc:mysql://114.115.223.227:3306/chatcove?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1304206691Lh
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
  # redis配置
    redis:
      # Redis数据库索引（默认为0）
      database: 1
      # Redis服务器地址
      host: 114.115.223.227
      password: 130420
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      # password:
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0

springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan:
        - com.cool.chatcove.controller

rocketmq:
  consumer:
    group: springboot_consumer_group
    pull-batch-size: 10
  name-server: 114.115.223.227:9876
  producer:
    group: springboot_producer_group
    send-message-timeout: 1000
    retry-times-when-send-failed: 2
    # 异步消息重试此处，默认2
    retry-times-when-send-async-failed: 2
    # 消息最大长度，默认1024 * 1024 * 4(默认4M)
    max-message-size: 4096
    # 压缩消息阈值，默认4k(1024 * 4)
    compress-message-body-threshold: 4096
    # 是否在内部发送失败时重试另一个broker，默认false
    retry-next-server: false

