server:
  port: 1211

spring:
  datasource:
    url: jdbc:mysql://114.115.223.227:3306/chatcove?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1304206691Lh
    driver-class-name: com.mysql.cj.jdbc.Driver